name: floodwatch
region: lon

static_sites:
  - name: floodwatch
    github:
      repo: aallan/floodwatch
      branch: main
      deploy_on_push: true
    environment_slug: html
    source_dir: /
    output_dir: /
    index_document: index.html
